name = "macha-generator"
version = "0.1.0"
description = "Web server for the Macha generator app"
authors = [
    "Martin Kratochvil <martvil96@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.7"
gunicorn = "^20.1.0"
